const path = require("path");
const { existsSync, readFileSync, writeFileSync } = require("fs");
const { values, positionals } = require("util").parseArgs({
	args: process.argv.slice(2),
	options: {
		profile: {
			type: "string"
		},
		target: {
			type: "string"
		}
	},
	strict: true,
	allowPositionals: true
});

const { spawn } = require("child_process");
const napiBin = path.resolve(
	__dirname,
	"../node_modules/.bin",
	process.platform === "win32" ? "napi.cmd" : "napi"
);
const pnpmBin = process.platform === "win32" ? "pnpm.cmd" : "pnpm";
const rootDir = path.resolve(__dirname, "../../..");
const bundleViewerAssetPath = path.join(
	rootDir,
	".generated",
	"bundle-viewer",
	"bundle-viewer.html"
);

const CARGO_SAFELY_EXIT_CODE = 0;

build().then((value) => {
	// Regarding cargo's non-zero exit code as an error.
	if (value !== CARGO_SAFELY_EXIT_CODE) {
		process.exit(value);
	}
}).catch(err => {
	console.error(err);
	process.exit(1);
});

async function build() {
	return new Promise((resolve, reject) => {
		let args = [
			"build",
			"--platform",
			"--js",
			"binding.js",
			"--dts",
			"binding.d.ts",
			// "--no-js",
			"--no-dts-header",
		];

		if (values.profile) {
			args.push("--profile", values.profile);
		}

		let features = [];
		prepareBundleViewerAsset()
			.then((envs) => {
				if (!envs.DISABLE_PLUGIN) {
					args.push("--no-default-features");
					features.push("plugin");
				}
				if (envs.RUST_TARGET) {
					args.push("--target", envs.RUST_TARGET);
				}
				args.push("--no-dts-cache");
				if (features.length) {
					args.push("--features", features.join(","));
				}

				if (positionals.length > 0) {
					// napi need `--` to separate options and positional arguments.
					args.push("--");
					args.push(...positionals);
				}

				console.log(`Run command: ${napiBin} ${args.join(" ")}`);

				let cp = spawn(napiBin, args, {
					stdio: "inherit",
					env: envs,
				});

				cp.on("error", reject);
				cp.on("exit", (code) => {
					if (code === CARGO_SAFELY_EXIT_CODE) {
						// Fix an issue where napi cli does not generate `string_enum` with `enum`s.
						let dts = path.resolve(__dirname, "../binding.d.ts");
						writeFileSync(dts,
							readFileSync(dts, "utf8")
								.replaceAll("const enum", "enum")
								// Remove the NormalModule type declaration generated by N-API.
								// We manually declare the NormalModule type in banner.d.ts
								// This allows users to extend NormalModule with static methods through type augmentation.
								.replaceAll(/export\s+declare\s+class\s+NormalModule\s*\{([\s\S]*?)\}\s*(?=\n\s*(?:export|declare|class|$))/g, "")
						);
					}
					resolve(code);
				});
			})
			.catch(reject);
	});
}

async function prepareBundleViewerAsset() {
	let envs = { ...process.env };

	if (envs.SPACK_BUNDLE_VIEWER_HTML) {
		return envs;
	}

	if (envs.CI) {
		throw new Error(
			"SPACK_BUNDLE_VIEWER_HTML must be set in CI. Download the bundle-viewer-html artifact before building the binding."
		);
	}

	await buildBundleViewerAsset();
	if (!existsSync(bundleViewerAssetPath)) {
		throw new Error(`Expected bundle viewer asset at ${bundleViewerAssetPath}, but it was not generated.`);
	}

	envs.SPACK_BUNDLE_VIEWER_HTML = bundleViewerAssetPath;
	return envs;
}

async function buildBundleViewerAsset() {
	return new Promise((resolve, reject) => {
		const cp = spawn(pnpmBin, ["--dir", rootDir, "run", "bundle-viewer:build-asset"], {
			stdio: "inherit",
			env: process.env,
		});

		cp.on("error", reject);
		cp.on("exit", (code) => {
			if (code === CARGO_SAFELY_EXIT_CODE) {
				resolve();
				return;
			}

			reject(new Error(`Failed to build bundle viewer asset, exit code: ${code}`));
		});
	});
}
