name: Debug
env:
  DEBUG: napi:*
  APP_NAME: doctor
  NAPI_DIR: napi/doctor
  CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG: true

permissions:
  contents: write
  id-token: write

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-platforms:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: crates/binding/artifacts

      - name: Show artifacts
        shell: bash
        run: |
          ls -R crates/binding/artifacts

      - name: Download Js
        uses: actions/download-artifact@v4
        with:
          name: js
          path: crates/binding
          merge-multiple: true

      - name: Show js
        shell: bash
        run: |
          ls -R crates/binding